"""
Tests for the Orbital Comparator plugin.

Adapted from tests/test_plugin_molecule_comparator.py — same shape (metadata,
entry points, document-reset handler, colour helper), but the subject compares
volumetric cube files rather than structures, so the substantive tests are
about cube parsing, grid construction and slot/render bookkeeping.

Cube reading is exercised against real numpy through ``mocks_with_real_numpy``:
a stubbed numpy would make ``reshape``/``outer`` return MagicMocks and every
geometry assertion would pass vacuously.
"""

from __future__ import annotations

import numpy as _ensure_real_numpy_imported  # noqa: F401
import pytest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import MagicMock

from conftest import (
    extract_function,
    load_plugin,
    make_context,
    mock_optional_imports,
    mocks_with_real_numpy,
)

PLUGINS_DIR = Path(__file__).resolve().parents[1] / "plugins"
ORBITAL_COMPARATOR_PATH = (
    PLUGINS_DIR / "Orbital_Comparator" / "orbital_comparator.py"
)


def _write_cube(tmp_path, name="mo.cube", stamp=None, dims=(2, 2, 2), n_atoms=1):
    """A minimal but well-formed cube file."""
    nx, ny, nz = dims
    header = stamp if stamp is not None else "Generated by ORCA Result Analyzer v3.13.2 | grid=40 | margin=4.00"
    lines = [
        "ORCA Analyzer Cube File: MO 5",
        header,
        f"{n_atoms} 0.000000 0.000000 0.000000",
        f"{nx} 0.500000 0.000000 0.000000",
        f"{ny} 0.000000 0.500000 0.000000",
        f"{nz} 0.000000 0.000000 0.500000",
    ]
    for _ in range(n_atoms):
        lines.append("8 8.000000 0.000000 0.000000 0.000000")
    values = [f"{v:.5E}" for v in range(nx * ny * nz)]
    lines.append(" ".join(values))
    path = tmp_path / name
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Metadata and entry points
# ---------------------------------------------------------------------------


class TestOrbitalComparatorMetadata:
    def test_declares_the_metadata_the_registry_reads(self):
        with mock_optional_imports():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
        assert mod.PLUGIN_NAME == "Orbital Comparator"
        assert mod.PLUGIN_AUTHOR == "HiroYokoyama"
        assert mod.PLUGIN_VERSION
        assert mod.PLUGIN_SUPPORTED_MOLEDITPY_VERSION

    def test_initialize_registers_document_reset_handler(self):
        with mock_optional_imports():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            ctx = make_context()
            mod.initialize(ctx)
            ctx.register_document_reset_handler.assert_called_once()

    def test_four_slots_have_distinct_default_colours(self):
        with mock_optional_imports():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
        assert len(mod.DEFAULT_COLORS) == mod.SLOT_COUNT
        positives = [c[0] for c in mod.DEFAULT_COLORS]
        assert len(set(positives)) == mod.SLOT_COUNT


class TestCubeViewerPrecedence:
    """The Cube File Viewers own .cube files; this plugin must never outrank
    them, or which plugin answers a drop or a command-line file would depend
    on plugin load order."""

    CUBE_VIEWERS = [
        PLUGINS_DIR / "Cube_File_Viewer" / "cube_viewer.py",
        PLUGINS_DIR / "Cube_File_Viewer_Advanced" / "cube_viewer_advanced.py",
    ]

    def _register_calls(self, path, method):
        with mock_optional_imports():
            mod = load_plugin(path)
            ctx = make_context()
            mod.initialize(ctx)
        return getattr(ctx, method).call_args_list

    def _opener_priority(self, call):
        if "priority" in call.kwargs:
            return call.kwargs["priority"]
        return call.args[3] if len(call.args) > 3 else 0

    def test_it_claims_no_main_window_drops_at_all(self):
        """Drops reach this plugin through its own window only."""
        calls = self._register_calls(ORBITAL_COMPARATOR_PATH, "register_drop_handler")
        assert calls == []

    def test_the_cube_viewers_still_claim_drops(self):
        """Guards the assumption above: if they stopped, this plugin taking no
        drops would leave main-window drops unhandled."""
        for path in self.CUBE_VIEWERS:
            if path.exists():
                assert self._register_calls(path, "register_drop_handler")

    def test_its_file_opener_sits_below_every_cube_viewer(self):
        mine = self._register_calls(ORBITAL_COMPARATOR_PATH, "register_file_opener")
        assert mine, "the fallback opener should still be registered"
        worst = max(self._opener_priority(c) for c in mine)

        for path in self.CUBE_VIEWERS:
            if not path.exists():
                continue
            for call in self._register_calls(path, "register_file_opener"):
                assert worst < self._opener_priority(call)

    def test_the_fallback_opener_covers_both_extensions(self):
        calls = self._register_calls(ORBITAL_COMPARATOR_PATH, "register_file_opener")
        assert {c.args[0] for c in calls} == {".cube", ".cub"}

    def test_the_opener_priority_is_negative(self):
        """The viewers register at the default 0, so equal is not below."""
        with mock_optional_imports():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
        assert mod.FILE_OPENER_PRIORITY < 0


class TestFallbackOpener:
    def test_it_opens_the_window_with_the_cube_loaded(self, tmp_path):
        from orbital_comparator_harness import load_with_stateful_qt

        mod = load_with_stateful_qt(ORBITAL_COMPARATOR_PATH)
        mw = SimpleNamespace(plotter=MagicMock())
        ctx = MagicMock()
        ctx.get_main_window.return_value = mw
        mod.initialize(ctx)

        opener = ctx.register_file_opener.call_args_list[0].args[1]
        opener(str(_write_cube(tmp_path, name="fallback.cube")))

        win = mw.orbital_comparator_window
        assert win.isVisible()
        assert win.slots[0].path.endswith("fallback.cube")

    def test_it_reuses_an_open_window(self, tmp_path):
        from orbital_comparator_harness import load_with_stateful_qt

        mod = load_with_stateful_qt(ORBITAL_COMPARATOR_PATH)
        mw = SimpleNamespace(plotter=MagicMock())
        ctx = MagicMock()
        ctx.get_main_window.return_value = mw
        mod.initialize(ctx)
        opener = ctx.register_file_opener.call_args_list[0].args[1]

        opener(str(_write_cube(tmp_path, name="a.cube")))
        first = mw.orbital_comparator_window
        opener(str(_write_cube(tmp_path, name="b.cube")))

        assert mw.orbital_comparator_window is first
        assert first.slots[1].path.endswith("b.cube")


class TestComparatorResetHandler:
    def _handler(self, mw):
        with mock_optional_imports():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            ctx = make_context()
            ctx.get_main_window.return_value = mw
            mod.initialize(ctx)
        return ctx.register_document_reset_handler.call_args[0][0]

    def test_reset_closes_open_window(self):
        mw = SimpleNamespace(orbital_comparator_window=MagicMock())
        handler = self._handler(mw)
        handler()
        mw.orbital_comparator_window.close.assert_called_once()

    def test_reset_noop_without_window(self):
        mw = SimpleNamespace()  # no orbital_comparator_window attribute
        handler = self._handler(mw)
        handler()  # must not raise


# ---------------------------------------------------------------------------
# contrast_text — pure string/math, extracted and run standalone
# ---------------------------------------------------------------------------


def _contrast_fn():
    return extract_function(ORBITAL_COMPARATOR_PATH, None, "contrast_text")


class TestContrastText:
    def test_dark_background_gives_white_text(self):
        fn = _contrast_fn()
        assert fn("#000080") == "white"

    def test_light_background_gives_black_text(self):
        fn = _contrast_fn()
        assert fn("#ffff00") == "black"

    def test_invalid_hex_falls_back_to_black(self):
        fn = _contrast_fn()
        assert fn("not_a_color") == "black"

    def test_non_hex_digits_fall_back_to_black(self):
        fn = _contrast_fn()
        assert fn("#zzzzzz") == "black"


# ---------------------------------------------------------------------------
# Generation settings recorded in the cube header
# ---------------------------------------------------------------------------


class TestGenerationSettings:
    def _fns(self):
        with mock_optional_imports():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
        return mod.read_generation_settings, mod.describe_settings

    def test_reads_grid_margin_and_version(self, tmp_path):
        read, _ = self._fns()
        info = read(str(_write_cube(tmp_path)))
        assert info["grid"] == 40
        assert info["margin"] == pytest.approx(4.00)
        assert info["version"] == "3.13.2"

    def test_a_foreign_cube_reports_everything_unknown(self, tmp_path):
        read, _ = self._fns()
        info = read(str(_write_cube(tmp_path, stamp="SCF density")))
        assert info == {"version": None, "grid": None, "margin": None}

    def test_a_missing_file_reports_everything_unknown(self, tmp_path):
        read, _ = self._fns()
        info = read(str(tmp_path / "nope.cube"))
        assert info == {"version": None, "grid": None, "margin": None}

    def test_description_names_the_settings(self):
        _, describe = self._fns()
        text = describe({"grid": 60, "margin": 5.5, "version": "3.13.2"})
        assert "60 pts" in text
        assert "5.50 Bohr" in text
        assert "3.13.2" in text

    def test_description_says_unknown_rather_than_guessing(self):
        """Never describe a foreign cube with plausible-looking defaults."""
        _, describe = self._fns()
        text = describe({"grid": None, "margin": None, "version": None})
        assert "unknown grid" in text
        assert "unknown margin" in text

    def test_description_reports_a_partial_stamp(self):
        _, describe = self._fns()
        text = describe({"grid": 40, "margin": None, "version": None})
        assert "40 pts" in text
        assert "unknown margin" in text


# ---------------------------------------------------------------------------
# Cube parsing — real numpy
# ---------------------------------------------------------------------------


class TestParseCube:
    def _parse(self):
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            return mod.parse_cube

    def test_reads_dimensions_and_origin(self, tmp_path):
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            meta = mod.parse_cube(str(_write_cube(tmp_path, dims=(2, 3, 4))))
        assert meta["dims"] == (2, 3, 4)
        assert list(meta["origin"]) == [0.0, 0.0, 0.0]

    def test_reads_every_data_point(self, tmp_path):
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            meta = mod.parse_cube(str(_write_cube(tmp_path, dims=(2, 3, 4))))
        assert len(meta["data"]) == 2 * 3 * 4

    def test_skips_the_atom_records(self, tmp_path):
        """Atom lines sit between the axes and the data; miscounting them
        shifts every value."""
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            meta = mod.parse_cube(str(_write_cube(tmp_path, n_atoms=3)))
        assert meta["data"][0] == 0.0
        assert meta["data"][-1] == 7.0

    def test_a_negative_atom_count_skips_the_dset_block(self, tmp_path):
        """An MO cube carries a DSET_IDS record the data does not include."""
        path = tmp_path / "mo.cube"
        path.write_text(
            "comment\nstamp\n-1 0.0 0.0 0.0\n"
            "2 0.5 0.0 0.0\n2 0.0 0.5 0.0\n2 0.0 0.0 0.5\n"
            "8 8.0 0.0 0.0 0.0\n"
            "1 7\n"
            + " ".join(str(float(v)) for v in range(8))
            + "\n",
            encoding="utf-8",
        )
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            meta = mod.parse_cube(str(path))
        assert len(meta["data"]) == 8
        assert meta["data"][0] == 0.0

    def test_interleaved_datasets_take_the_first_orbital(self, tmp_path):
        """Two orbitals in one cube interleave point by point; reshaping the
        whole stream would raise, and taking a contiguous half would mix
        them."""
        path = tmp_path / "two.cube"
        values = []
        for i in range(8):
            values += [float(i), 900.0 + i]  # orbital 0, orbital 1
        path.write_text(
            "comment\nstamp\n-1 0.0 0.0 0.0\n"
            "2 0.5 0.0 0.0\n2 0.0 0.5 0.0\n2 0.0 0.0 0.5\n"
            "8 8.0 0.0 0.0 0.0\n"
            "2 7 8\n" + " ".join(str(v) for v in values) + "\n",
            encoding="utf-8",
        )
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            meta = mod.parse_cube(str(path))
        assert len(meta["data"]) == 8
        assert list(meta["data"]) == [float(i) for i in range(8)]

    def test_a_negative_voxel_count_flags_angstrom(self, tmp_path):
        """Gaussian marks Angstrom grids with a negative NX; treating those as
        Bohr inflates the isosurface by 1.89x."""
        path = tmp_path / "ang.cube"
        path.write_text(
            "comment\nstamp\n1 0.0 0.0 0.0\n"
            "-2 0.5 0.0 0.0\n2 0.0 0.5 0.0\n2 0.0 0.0 0.5\n"
            "8 8.0 0.0 0.0 0.0\n"
            + " ".join(str(float(v)) for v in range(8))
            + "\n",
            encoding="utf-8",
        )
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            meta = mod.parse_cube(str(path))
        assert meta["is_angstrom"] is True
        assert meta["dims"] == (2, 2, 2)

    def test_a_blank_line_in_the_dset_block_does_not_hang(self, tmp_path):
        """A line consuming no ids used to spin the loop forever, freezing the
        whole app on a malformed file."""
        path = tmp_path / "blank.cube"
        path.write_text(
            "comment\nstamp\n-1 0.0 0.0 0.0\n"
            "2 0.5 0.0 0.0\n2 0.0 0.5 0.0\n2 0.0 0.0 0.5\n"
            "8 8.0 0.0 0.0 0.0\n"
            "3\n"
            "\n"
            "7 8 9\n" + " ".join(str(float(v)) for v in range(24)) + "\n",
            encoding="utf-8",
        )
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            meta = mod.parse_cube(str(path))
        assert len(meta["data"]) == 8

    def test_a_cube_ending_inside_its_dset_block_raises(self, tmp_path):
        path = tmp_path / "cut.cube"
        path.write_text(
            "comment\nstamp\n-1 0.0 0.0 0.0\n"
            "2 0.5 0.0 0.0\n2 0.0 0.5 0.0\n2 0.0 0.0 0.5\n"
            "8 8.0 0.0 0.0 0.0\n"
            "5\n",
            encoding="utf-8",
        )
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            with pytest.raises(ValueError):
                mod.parse_cube(str(path))

    def test_a_truncated_cube_raises_rather_than_returning_junk(self, tmp_path):
        path = tmp_path / "bad.cube"
        path.write_text("comment\nstamp\n", encoding="utf-8")
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)
            with pytest.raises((IndexError, ValueError)):
                mod.parse_cube(str(path))


class TestBuildGrid:
    def _grid_points(self, meta_overrides=None):
        """build_grid against a fake pyvista StructuredGrid that keeps state."""
        with mocks_with_real_numpy():
            mod = load_plugin(ORBITAL_COMPARATOR_PATH)

            class _Grid:
                def __init__(self):
                    self.points = None
                    self.dimensions = None
                    self.point_data = {}

            mod.pv = SimpleNamespace(StructuredGrid=_Grid)
            meta = {
                "dims": (2, 2, 2),
                "origin": mod.np.array([0.0, 0.0, 0.0]),
                "vectors": (
                    mod.np.array([1.0, 0.0, 0.0]),
                    mod.np.array([0.0, 1.0, 0.0]),
                    mod.np.array([0.0, 0.0, 1.0]),
                ),
                "data": mod.np.arange(8, dtype=float),
                "is_angstrom": False,
            }
            meta.update(meta_overrides or {})
            return mod, mod.build_grid(meta)

    def test_bohr_grids_are_converted_to_angstrom(self):
        mod, grid = self._grid_points()
        # One Bohr step along x becomes 0.529 A.
        xs = sorted({p[0] for p in grid.points})
        assert xs[1] == pytest.approx(0.529177249)

    def test_angstrom_grids_are_left_alone(self):
        mod, grid = self._grid_points({"is_angstrom": True})
        xs = sorted({p[0] for p in grid.points})
        assert xs[1] == pytest.approx(1.0)

    def test_dimensions_are_passed_through(self):
        _mod, grid = self._grid_points()
        assert list(grid.dimensions) == [2, 2, 2]

    def test_values_are_reordered_for_the_point_layout(self):
        """Cube data is Z-fastest, grid points are X-fastest; skipping the
        reorder silently mirrors the orbital."""
        _mod, grid = self._grid_points()
        assert list(grid.point_data["values"]) == [0, 4, 2, 6, 1, 5, 3, 7]


# ---------------------------------------------------------------------------
# Slot behaviour, extracted from the Qt class
# ---------------------------------------------------------------------------


def _slot_fn(name):
    return extract_function(ORBITAL_COMPARATOR_PATH, "CubeSlot", name)


class TestSlotColour:
    def test_the_colour_round_trips_through_the_stylesheet(self):
        set_color = _slot_fn("set_color")
        color = _slot_fn("color")
        contrast = _contrast_fn()

        class _Btn:
            def __init__(self):
                self._s = ""

            def setStyleSheet(self, s):
                self._s = s

            def styleSheet(self):
                return self._s

        slot = SimpleNamespace(btn_p=_Btn(), btn_n=_Btn())
        set_color.__globals__["contrast_text"] = contrast
        set_color(slot, "p", "#123456")
        assert color(slot, "p") == "#123456"

    def test_an_unstyled_button_reports_a_default(self):
        color = _slot_fn("color")

        class _Btn:
            def styleSheet(self):
                return ""

        slot = SimpleNamespace(btn_p=_Btn(), btn_n=_Btn())
        assert color(slot, "p") == "#ff0000"
        assert color(slot, "n") == "#0000ff"

    def test_a_slot_without_a_grid_is_never_shown(self):
        """The checkbox alone must not put an empty slot on screen."""
        is_on = _slot_fn("is_on")
        slot = SimpleNamespace(
            check_on=SimpleNamespace(isChecked=lambda: True), grid=None
        )
        assert is_on(slot) is False

    def test_a_loaded_but_unticked_slot_is_not_shown(self):
        is_on = _slot_fn("is_on")
        slot = SimpleNamespace(
            check_on=SimpleNamespace(isChecked=lambda: False), grid=object()
        )
        assert is_on(slot) is False

    def test_a_loaded_and_ticked_slot_is_shown(self):
        is_on = _slot_fn("is_on")
        slot = SimpleNamespace(
            check_on=SimpleNamespace(isChecked=lambda: True), grid=object()
        )
        assert is_on(slot) is True


# ---------------------------------------------------------------------------
# Window behaviour — ported from the ORCA Result Analyzer's comparison-window
# suite (tests/test_mo_compare.py there), which covers the same slot model:
# live redraw on cheap settings, per-slot actor namespaces, iso syncing and
# teardown. Run against stateful Qt stubs so the window is a real instance.
# ---------------------------------------------------------------------------


class _FakeMesh:
    def __init__(self, n_points=10):
        self.n_points = n_points


class _FakeGrid:
    """Stands in for the pyvista StructuredGrid a cube parses into."""

    def __init__(self):
        self.contour_levels = []

    def contour(self, levels, scalars=None):
        self.contour_levels.append(levels[0])
        return _FakeMesh()


@pytest.fixture
def comparator(tmp_path):
    """A live OrbitalComparator with a mocked plotter."""
    from orbital_comparator_harness import load_with_stateful_qt

    mod = load_with_stateful_qt(ORBITAL_COMPARATOR_PATH)
    mw = SimpleNamespace(plotter=MagicMock())
    ctx = MagicMock()
    ctx.get_main_window.return_value = mw
    win = mod.OrbitalComparator(ctx)
    return SimpleNamespace(mod=mod, win=win, mw=mw, tmp=tmp_path)


def _fill(env, index, iso=0.02):
    """Put a loaded cube into a slot without touching the filesystem."""
    slot = env.win.slots[index]
    slot.grid = _FakeGrid()
    slot.path = f"/cubes/mo{index}.cube"
    slot.settings = {"grid": 40, "margin": 4.0, "version": "3.13.2"}
    slot.check_on.setChecked(True)
    slot.spin_iso.setValue(iso)
    return slot


def _meshes(env):
    """Actor names the plotter was asked to draw."""
    return [
        c.kwargs["name"]
        for c in env.mw.plotter.add_mesh.call_args_list
        if "name" in c.kwargs
    ]


class TestWindowConstruction:
    def test_it_builds_four_slots(self, comparator):
        assert len(comparator.win.slots) == comparator.mod.SLOT_COUNT

    def test_each_slot_gets_its_own_actor_namespace(self, comparator):
        prefixes = [s.prefix for s in comparator.win.slots]
        assert len(set(prefixes)) == comparator.mod.SLOT_COUNT

    def test_slots_start_empty(self, comparator):
        assert all(s.grid is None for s in comparator.win.slots)
        assert not any(s.is_on() for s in comparator.win.slots)

    def test_the_status_line_says_nothing_is_loaded(self, comparator):
        assert "No cubes" in comparator.win.lbl_status.text()

    def test_slot_colours_start_distinct(self, comparator):
        pos = [s.color("p") for s in comparator.win.slots]
        assert len(set(pos)) == comparator.mod.SLOT_COUNT


class TestRendering:
    def test_a_loaded_slot_draws_both_lobes(self, comparator):
        _fill(comparator, 0)
        comparator.win.render_all()
        assert "orb_cmp0_p" in _meshes(comparator)
        assert "orb_cmp0_n" in _meshes(comparator)

    def test_four_cubes_draw_at_once_under_distinct_names(self, comparator):
        for i in range(4):
            _fill(comparator, i)
        comparator.win.render_all()
        names = _meshes(comparator)
        for i in range(4):
            assert f"orb_cmp{i}_p" in names

    def test_the_contour_uses_the_slot_isovalue(self, comparator):
        slot = _fill(comparator, 0, iso=0.055)
        comparator.win.render_all()
        assert slot.grid.contour_levels[0] == pytest.approx(0.055)

    def test_the_negative_lobe_uses_the_mirrored_level(self, comparator):
        slot = _fill(comparator, 0, iso=0.03)
        comparator.win.render_all()
        assert slot.grid.contour_levels[1] == pytest.approx(-0.03)

    def test_each_slot_renders_with_its_own_colour(self, comparator):
        _fill(comparator, 0)
        _fill(comparator, 1)
        comparator.win.slots[1].set_color("p", "#00ff00")
        comparator.win.render_all()
        colors = {
            c.kwargs["name"]: c.kwargs["color"]
            for c in comparator.mw.plotter.add_mesh.call_args_list
        }
        assert colors["orb_cmp1_p"] == "#00ff00"
        assert colors["orb_cmp0_p"] != "#00ff00"

    def test_the_style_is_lower_cased_for_pyvista(self, comparator):
        slot = _fill(comparator, 0)
        slot.combo_style.setCurrentText("Wireframe")
        comparator.win.render_all()
        styles = {
            c.kwargs["name"]: c.kwargs["style"]
            for c in comparator.mw.plotter.add_mesh.call_args_list
        }
        assert styles["orb_cmp0_p"] == "wireframe"

    def test_an_unticked_slot_is_removed_not_drawn(self, comparator):
        slot = _fill(comparator, 0)
        slot.check_on.setChecked(False)
        comparator.win.render_all()
        assert "orb_cmp0_p" not in _meshes(comparator)
        removed = [c[0][0] for c in comparator.mw.plotter.remove_actor.call_args_list]
        assert "orb_cmp0_p" in removed

    def test_an_empty_slot_is_never_drawn(self, comparator):
        comparator.win.slots[0].check_on.setChecked(True)  # ticked, but no cube
        comparator.win.render_all()
        assert _meshes(comparator) == []

    def test_an_empty_mesh_is_skipped(self, comparator):
        """A contour level above the data maximum yields no geometry."""
        slot = _fill(comparator, 0)
        slot.grid.contour = lambda levels, scalars=None: _FakeMesh(n_points=0)
        comparator.win.render_all()
        assert _meshes(comparator) == []

    def test_a_broken_grid_does_not_take_the_window_down(self, comparator):
        slot = _fill(comparator, 0)

        def boom(levels, scalars=None):
            raise ValueError("bad scalars")

        slot.grid.contour = boom
        comparator.win.render_all()  # must not raise
        assert _meshes(comparator) == []

    def test_the_status_line_counts_loaded_and_shown(self, comparator):
        _fill(comparator, 0)
        _fill(comparator, 1)
        comparator.win.slots[1].check_on.setChecked(False)
        comparator.win.render_all()
        assert "2 cube(s) loaded, 1 shown" in comparator.win.lbl_status.text()

    def test_rendering_without_a_plotter_is_a_no_op(self, comparator):
        _fill(comparator, 0)
        comparator.win.mw = SimpleNamespace()
        comparator.win.render_all()  # must not raise


class TestLiveRedraw:
    """Contouring a grid already in memory is cheap, so these apply at once."""

    def _armed(self, env):
        env.mw.plotter.add_mesh.reset_mock()

    def test_changing_the_isovalue_redraws(self, comparator):
        slot = _fill(comparator, 0)
        self._armed(comparator)
        slot.spin_iso.valueChanged.emit(0.05)
        assert "orb_cmp0_p" in _meshes(comparator)

    def test_changing_the_opacity_redraws(self, comparator):
        slot = _fill(comparator, 0)
        self._armed(comparator)
        slot.spin_opacity.valueChanged.emit(0.9)
        assert "orb_cmp0_p" in _meshes(comparator)

    def test_changing_the_style_redraws(self, comparator):
        slot = _fill(comparator, 0)
        self._armed(comparator)
        slot.combo_style.currentTextChanged.emit("Points")
        assert "orb_cmp0_p" in _meshes(comparator)

    def test_toggling_smooth_shading_redraws(self, comparator):
        slot = _fill(comparator, 0)
        self._armed(comparator)
        slot.check_smooth.toggled.emit(False)
        assert "orb_cmp0_p" in _meshes(comparator)

    def test_toggling_show_redraws(self, comparator):
        slot = _fill(comparator, 0)
        self._armed(comparator)
        slot.check_on.toggled.emit(True)
        assert "orb_cmp0_p" in _meshes(comparator)

    def test_a_half_built_window_never_renders(self, comparator):
        _fill(comparator, 0)
        comparator.win._ready = False
        self._armed(comparator)
        comparator.win.on_live_change()
        assert _meshes(comparator) == []

    def test_a_suspended_batch_does_not_render(self, comparator):
        """Real Qt setters DO emit, unlike these stubs, so the guard is what
        keeps a multi-widget update to a single redraw."""
        _fill(comparator, 0)
        self._armed(comparator)
        comparator.win._suspend += 1
        try:
            comparator.win.render_all()
        finally:
            comparator.win._suspend -= 1
        assert _meshes(comparator) == []

    def test_the_guard_is_balanced_after_a_batch(self, comparator):
        _fill(comparator, 0)
        comparator.win.sync_isovalue()
        assert comparator.win._suspend == 0


class TestSyncIsovalue:
    def test_every_slot_takes_cube_ones_isovalue(self, comparator):
        for i in range(4):
            _fill(comparator, i, iso=0.01 * (i + 1))
        comparator.win.slots[0].spin_iso.setValue(0.066)
        comparator.win.sync_isovalue()
        assert all(
            s.spin_iso.value() == pytest.approx(0.066) for s in comparator.win.slots
        )

    def test_other_settings_stay_independent(self, comparator):
        _fill(comparator, 0)
        slot = _fill(comparator, 1)
        slot.set_color("p", "#00ff00")
        slot.spin_opacity.setValue(0.9)
        comparator.win.sync_isovalue()
        assert slot.color("p") == "#00ff00"
        assert slot.spin_opacity.value() == pytest.approx(0.9)

    def test_syncing_redraws_at_the_new_level(self, comparator):
        _fill(comparator, 0, iso=0.07)
        slot = _fill(comparator, 1, iso=0.01)
        comparator.mw.plotter.add_mesh.reset_mock()
        slot.grid.contour_levels.clear()
        comparator.win.sync_isovalue()
        assert slot.grid.contour_levels[0] == pytest.approx(0.07)

    def test_syncing_with_no_slots_is_harmless(self, comparator):
        comparator.win.slots = []
        comparator.win.sync_isovalue()  # must not raise


class TestLoading:
    def test_a_cube_file_loads_into_a_slot(self, comparator):
        path = _write_cube(comparator.tmp)
        assert comparator.win.load_into(comparator.win.slots[0], str(path)) is True
        assert comparator.win.slots[0].grid is not None

    def test_loading_ticks_the_slot_on(self, comparator):
        path = _write_cube(comparator.tmp)
        comparator.win.load_into(comparator.win.slots[0], str(path))
        assert comparator.win.slots[0].is_on()

    def test_the_slot_reports_the_file_and_its_settings(self, comparator):
        path = _write_cube(comparator.tmp, name="homo.cube")
        comparator.win.load_into(comparator.win.slots[0], str(path))
        text = comparator.win.slots[0].lbl_info.text()
        assert "homo.cube" in text
        assert "40 pts" in text

    def test_a_foreign_cube_reports_unknown_settings(self, comparator):
        path = _write_cube(comparator.tmp, stamp="SCF density")
        comparator.win.load_into(comparator.win.slots[0], str(path))
        assert "unknown" in comparator.win.slots[0].lbl_info.text()

    def test_an_unreadable_file_is_reported_and_leaves_the_slot_empty(
        self, comparator
    ):
        bad = comparator.tmp / "bad.cube"
        bad.write_text("not a cube\n", encoding="utf-8")
        comparator.mod.QMessageBox = MagicMock()
        assert comparator.win.load_into(comparator.win.slots[0], str(bad)) is False
        assert comparator.win.slots[0].grid is None
        comparator.mod.QMessageBox.warning.assert_called_once()

    def test_cancelling_the_file_dialog_loads_nothing(self, comparator):
        comparator.mod.QFileDialog = MagicMock()
        comparator.mod.QFileDialog.getOpenFileName.return_value = ("", "")
        assert comparator.win.load_into(comparator.win.slots[0]) is False
        assert comparator.win.slots[0].grid is None

    def test_several_files_fill_the_empty_slots_in_order(self, comparator):
        paths = [
            str(_write_cube(comparator.tmp, name=f"c{i}.cube")) for i in range(3)
        ]
        assert comparator.win.load_paths(paths) == 3
        loaded = [s.path for s in comparator.win.slots if s.grid is not None]
        assert len(loaded) == 3
        assert loaded[0].endswith("c0.cube")

    def test_more_files_than_slots_says_so(self, comparator):
        paths = [
            str(_write_cube(comparator.tmp, name=f"c{i}.cube")) for i in range(6)
        ]
        comparator.win.load_paths(paths)
        assert "only 4" in comparator.win.lbl_status.text()

    def test_loading_fills_empty_slots_before_overwriting(self, comparator):
        first = str(_write_cube(comparator.tmp, name="first.cube"))
        comparator.win.load_paths([first])
        second = str(_write_cube(comparator.tmp, name="second.cube"))
        comparator.win.load_paths([second])
        assert comparator.win.slots[0].path.endswith("first.cube")
        assert comparator.win.slots[1].path.endswith("second.cube")

    def test_a_loaded_cube_is_drawn_straight_away(self, comparator):
        path = _write_cube(comparator.tmp)
        comparator.win.load_into(comparator.win.slots[0], str(path))
        assert "orb_cmp0_p" in _meshes(comparator)


class TestRunEntryPoint:
    def _module(self):
        from orbital_comparator_harness import load_with_stateful_qt

        return load_with_stateful_qt(ORBITAL_COMPARATOR_PATH)

    def _ready_module(self, mw):
        mod = self._module()
        ctx = MagicMock()
        ctx.get_main_window.return_value = mw
        mod.initialize(ctx)
        return mod

    def test_the_first_run_builds_and_stores_the_window(self):
        mw = SimpleNamespace(plotter=MagicMock())
        mod = self._ready_module(mw)
        mod.run(mw)
        assert isinstance(mw.orbital_comparator_window, mod.OrbitalComparator)

    def test_the_window_is_shown(self):
        mw = SimpleNamespace(plotter=MagicMock())
        mod = self._ready_module(mw)
        mod.run(mw)
        assert mw.orbital_comparator_window.isVisible()

    def test_running_again_toggles_it_closed(self):
        mw = SimpleNamespace(plotter=MagicMock())
        mod = self._ready_module(mw)
        mod.run(mw)
        first = mw.orbital_comparator_window
        mod.run(mw)
        assert mw.orbital_comparator_window is first
        assert not first.isVisible()

    def test_it_reuses_the_existing_window(self):
        mw = SimpleNamespace(plotter=MagicMock())
        mod = self._ready_module(mw)
        mod.run(mw)
        first = mw.orbital_comparator_window
        mod.run(mw)  # closes
        mod.run(mw)  # reopens the same instance
        assert mw.orbital_comparator_window is first
        assert first.isVisible()

    def test_a_wrapped_main_window_is_unwrapped(self):
        """The host passes a wrapper carrying the real window as .host."""
        real = SimpleNamespace(plotter=MagicMock())
        mod = self._ready_module(real)
        mod.run(SimpleNamespace(host=real))
        assert hasattr(real, "orbital_comparator_window")

    def test_running_without_initialize_does_nothing(self):
        mw = SimpleNamespace(plotter=MagicMock())
        mod = self._module()  # PLUGIN_CONTEXT still None
        mod.run(mw)
        assert not hasattr(mw, "orbital_comparator_window")


class TestMissingDependencies:
    def test_reading_without_numpy_is_reported_not_crashed(self, comparator):
        path = str(_write_cube(comparator.tmp))
        comparator.mod.np = None
        comparator.mod.QMessageBox = MagicMock()
        assert comparator.win.load_into(comparator.win.slots[0], path) is False
        comparator.mod.QMessageBox.warning.assert_called_once()

    def test_reading_without_pyvista_is_reported_not_crashed(self, comparator):
        path = str(_write_cube(comparator.tmp))
        comparator.mod.pv = None
        comparator.mod.QMessageBox = MagicMock()
        assert comparator.win.load_into(comparator.win.slots[0], path) is False
        comparator.mod.QMessageBox.warning.assert_called_once()


class TestLoadMany:
    def test_the_chosen_files_are_loaded(self, comparator):
        paths = [
            str(_write_cube(comparator.tmp, name=f"m{i}.cube")) for i in range(2)
        ]
        comparator.mod.QFileDialog = MagicMock()
        comparator.mod.QFileDialog.getOpenFileNames.return_value = (paths, "")
        comparator.win.load_many()
        assert comparator.win.slots[0].path.endswith("m0.cube")
        assert comparator.win.slots[1].path.endswith("m1.cube")

    def test_cancelling_loads_nothing(self, comparator):
        comparator.mod.QFileDialog = MagicMock()
        comparator.mod.QFileDialog.getOpenFileNames.return_value = ([], "")
        comparator.win.load_many()
        assert all(s.grid is None for s in comparator.win.slots)


class TestSlotDescription:
    def test_an_empty_slot_says_it_has_no_file(self, comparator):
        assert comparator.win.slots[0].describe() == "no file"

    def test_a_loaded_slot_names_the_file(self, comparator):
        path = str(_write_cube(comparator.tmp, name="lumo.cube"))
        comparator.win.load_into(comparator.win.slots[0], path)
        assert "lumo.cube" in comparator.win.slots[0].describe()

    def test_the_group_box_title_follows_the_file(self, comparator):
        path = str(_write_cube(comparator.tmp, name="lumo.cube"))
        comparator.win.load_into(comparator.win.slots[0], path)
        assert "lumo.cube" in comparator.win.slots[0].box.title()

    def test_clearing_restores_the_empty_title(self, comparator):
        path = str(_write_cube(comparator.tmp, name="lumo.cube"))
        comparator.win.load_into(comparator.win.slots[0], path)
        comparator.win.clear_slot(comparator.win.slots[0])
        assert "(empty)" in comparator.win.slots[0].box.title()


class TestClearing:
    def test_clearing_a_slot_empties_it(self, comparator):
        _fill(comparator, 0)
        comparator.win.clear_slot(comparator.win.slots[0])
        assert comparator.win.slots[0].grid is None
        assert comparator.win.slots[0].path is None

    def test_clearing_a_slot_removes_its_actors(self, comparator):
        _fill(comparator, 0)
        comparator.win.clear_slot(comparator.win.slots[0])
        removed = [c[0][0] for c in comparator.mw.plotter.remove_actor.call_args_list]
        assert "orb_cmp0_p" in removed
        assert "orb_cmp0_n" in removed

    def test_clearing_a_slot_leaves_the_others_alone(self, comparator):
        _fill(comparator, 0)
        _fill(comparator, 1)
        comparator.win.clear_slot(comparator.win.slots[0])
        assert comparator.win.slots[1].grid is not None

    def test_clear_all_empties_every_slot(self, comparator):
        for i in range(4):
            _fill(comparator, i)
        comparator.win.clear_all()
        assert all(s.grid is None for s in comparator.win.slots)

    def test_clear_all_resets_the_status_line(self, comparator):
        _fill(comparator, 0)
        comparator.win.clear_all()
        assert "No cubes" in comparator.win.lbl_status.text()


class TestColourPicking:
    def _pick(self, env, slot, which, hex_c, valid=True):
        chosen = MagicMock()
        chosen.isValid.return_value = valid
        chosen.name.return_value = hex_c
        env.mod.QColorDialog = MagicMock()
        env.mod.QColorDialog.getColor.return_value = chosen
        env.win.pick_color(slot, which)

    def test_a_chosen_colour_is_stored(self, comparator):
        slot = _fill(comparator, 2)
        self._pick(comparator, slot, "p", "#abcdef")
        assert slot.color("p") == "#abcdef"

    def test_cancelling_leaves_the_colour_alone(self, comparator):
        slot = _fill(comparator, 2)
        before = slot.color("p")
        self._pick(comparator, slot, "p", "#abcdef", valid=False)
        assert slot.color("p") == before

    def test_choosing_a_colour_redraws(self, comparator):
        slot = _fill(comparator, 0)
        comparator.mw.plotter.add_mesh.reset_mock()
        self._pick(comparator, slot, "n", "#abcdef")
        assert "orb_cmp0_n" in _meshes(comparator)

    def test_a_colour_only_affects_its_own_slot(self, comparator):
        _fill(comparator, 0)
        slot = _fill(comparator, 1)
        other = comparator.win.slots[0].color("p")
        self._pick(comparator, slot, "p", "#abcdef")
        assert comparator.win.slots[0].color("p") == other


class TestDragAndDrop:
    def _event(self, paths):
        mime = MagicMock()
        mime.hasUrls.return_value = bool(paths)
        mime.urls.return_value = [
            SimpleNamespace(toLocalFile=lambda p=p: p) for p in paths
        ]
        event = MagicMock()
        event.mimeData.return_value = mime
        return event

    def test_dropping_cube_files_loads_them(self, comparator):
        path = str(_write_cube(comparator.tmp))
        comparator.win.dropEvent(self._event([path]))
        assert comparator.win.slots[0].grid is not None

    def test_dropping_other_files_is_ignored(self, comparator):
        comparator.win.dropEvent(self._event(["/tmp/notes.txt"]))
        assert all(s.grid is None for s in comparator.win.slots)

    def test_a_drop_without_urls_is_ignored(self, comparator):
        comparator.win.dropEvent(self._event([]))
        assert all(s.grid is None for s in comparator.win.slots)

    def test_dragging_cube_files_is_accepted(self, comparator):
        event = self._event(["/cubes/a.cube"])
        comparator.win.dragEnterEvent(event)
        event.acceptProposedAction.assert_called_once()


class TestTeardown:
    def test_closing_removes_every_actor(self, comparator):
        for i in range(4):
            _fill(comparator, i)
        comparator.win.closeEvent(MagicMock())
        removed = [c[0][0] for c in comparator.mw.plotter.remove_actor.call_args_list]
        for i in range(4):
            assert f"orb_cmp{i}_p" in removed
            assert f"orb_cmp{i}_n" in removed

    def test_closing_accepts_the_event(self, comparator):
        event = MagicMock()
        comparator.win.closeEvent(event)
        event.accept.assert_called_once()

    def test_closing_without_a_plotter_is_harmless(self, comparator):
        comparator.win.mw = SimpleNamespace()
        comparator.win.closeEvent(MagicMock())  # must not raise
