"""
Tests for the MOPAC Input Generator plugin: generate_content (keyword line,
multiplicity keywords, 1SCF opt flags), preset save/load round-trip.

MopacSetupDialog inherits QDialog (mocked -> MagicMock), so methods are
extracted standalone via AST and invoked with fake self objects that mimic
only the widgets each method touches.
"""

from __future__ import annotations

import ast
import json
import logging
import os
import textwrap
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from conftest import load_plugin, mock_optional_imports

PLUGINS_DIR = Path(__file__).resolve().parents[1] / "plugins"
MOPAC_PATH = PLUGINS_DIR / "Mopac_Input_Generator" / "mopac_input_generator.py"


def _extract_method_as_fn(
    path: Path,
    class_name: str,
    method_name: str,
    extra_globals: dict | None = None,
):
    """
    Use AST to extract a class method as a standalone callable.

    Needed because Qt base classes are MagicMock instances whose metaclass call
    returns a MagicMock instead of a real type, so the class definition doesn't
    produce a usable type and object.__new__ fails.
    """
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            for item in node.body:
                if (
                    isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))
                    and item.name == method_name
                ):
                    func_src = ast.get_source_segment(source, item)
                    if func_src:
                        local_ns: dict = {}
                        globs = {"logging": logging, "os": os, "json": json}
                        globs.update(extra_globals or {})
                        exec(textwrap.dedent(func_src), globs, local_ns)
                        return local_ns[method_name]
    return None


class FakeSpin:
    def __init__(self, val):
        self._val = val

    def value(self):
        return self._val


class FakeCombo:
    def __init__(self, text, index=0):
        self._text = text
        self._index = index

    def currentText(self):
        return self._text

    def currentIndex(self):
        return self._index


class FakeCheck:
    def __init__(self, checked=False):
        self._checked = checked

    def isChecked(self):
        return self._checked


class FakeLine:
    def __init__(self, text=""):
        self._text = text

    def text(self):
        return self._text


class FakeText:
    def __init__(self, text=""):
        self._text = text

    def toPlainText(self):
        return self._text


class FakePos:
    def __init__(self, x, y, z):
        self.x, self.y, self.z = x, y, z


class FakeAtom:
    def __init__(self, symbol, num=6, props=None):
        self._symbol = symbol
        self._num = num
        self._props = props or {}

    def GetSymbol(self):
        return self._symbol

    def GetAtomicNum(self):
        return self._num

    def HasProp(self, key):
        return key in self._props

    def GetProp(self, key):
        return self._props[key]


class FakeConf:
    def __init__(self, coords):
        self._coords = coords

    def GetAtomPosition(self, i):
        return FakePos(*self._coords[i])


class FakeMol:
    def __init__(self, atoms, coords):
        assert len(atoms) == len(coords)
        self._atoms = atoms
        self._coords = coords

    def GetNumAtoms(self):
        return len(self._atoms)

    def GetAtomWithIdx(self, i):
        return self._atoms[i]

    def GetConformer(self):
        return FakeConf(self._coords)


def water_mol():
    return FakeMol(
        [FakeAtom("O", 8), FakeAtom("H", 1), FakeAtom("H", 1)],
        [(0.0, 0.0, 0.117), (0.0, 0.757, -0.469), (0.0, -0.757, -0.469)],
    )

_mopac_generate = _extract_method_as_fn(
    MOPAC_PATH, "MopacSetupDialog", "generate_content"
)


def _mopac_self(
    keywords="PM7 PRECISE",
    charge=0,
    mult=1,
    nosym=False,
    title="MOPAC Calculation",
    comment="Generated by MoleditPy",
    mol=None,
):
    self = MagicMock()
    self.keywords_edit = FakeLine(keywords)
    self.charge_spin = FakeSpin(charge)
    self.mult_spin = FakeSpin(mult)
    self.chk_nosym = FakeCheck(nosym)
    self.title_edit = FakeLine(title)
    self.comment_edit = FakeLine(comment)
    self.mol = mol
    return self


class TestMopacGenerateContent:
    def test_extraction_succeeded(self):
        assert _mopac_generate is not None

    def test_header_lines(self):
        content = _mopac_generate(_mopac_self())
        lines = content.split("\n")
        assert lines[0].startswith("PM7 PRECISE CHARGE=0")
        assert lines[1] == "MOPAC Calculation"
        assert lines[2] == "Generated by MoleditPy"

    def test_negative_charge_in_keywords(self):
        content = _mopac_generate(_mopac_self(charge=-2))
        assert "CHARGE=-2" in content.split("\n")[0]

    @pytest.mark.parametrize(
        "mult,expected",
        [
            (1, "SINGLET"),
            (2, "DOUBLET"),
            (3, "TRIPLET"),
            (4, "QUARTET"),
            (5, "QUINTET"),
            (6, "SEXTET"),
        ],
    )
    def test_named_multiplicity_keywords(self, mult, expected):
        content = _mopac_generate(_mopac_self(mult=mult))
        assert expected in content.split("\n")[0]

    @pytest.mark.parametrize("mult,ms", [(7, "MS=3.0"), (8, "MS=3.5"), (10, "MS=4.5")])
    def test_high_multiplicity_uses_ms(self, mult, ms):
        content = _mopac_generate(_mopac_self(mult=mult))
        assert ms in content.split("\n")[0]

    def test_nosym_appended_when_checked(self):
        assert "NOSYM" in _mopac_generate(_mopac_self(nosym=True)).split("\n")[0]
        assert "NOSYM" not in _mopac_generate(_mopac_self(nosym=False)).split("\n")[0]

    def test_no_molecule_gives_three_lines(self):
        content = _mopac_generate(_mopac_self(mol=None))
        assert len(content.split("\n")) == 3

    def test_geometry_lines_with_opt_flag_1(self):
        content = _mopac_generate(_mopac_self(mol=water_mol()))
        lines = content.split("\n")
        assert len(lines) == 6
        assert lines[3].startswith("O")
        # optimization flag 1 between coordinates
        assert lines[3].split()[2] == "1"
        assert lines[3].split()[4] == "1"
        assert lines[3].split()[6] == "1"

    def test_1scf_gives_fixed_geometry_flag_0(self):
        content = _mopac_generate(_mopac_self(keywords="PM7 1SCF", mol=water_mol()))
        atom_line = content.split("\n")[3]
        assert atom_line.split()[2] == "0"
        assert atom_line.split()[4] == "0"

    def test_1scf_detection_case_insensitive(self):
        content = _mopac_generate(_mopac_self(keywords="pm7 1scf", mol=water_mol()))
        assert content.split("\n")[3].split()[2] == "0"

    def test_coordinate_formatting(self):
        content = _mopac_generate(_mopac_self(mol=water_mol()))
        line = content.split("\n")[4]
        parts = line.split()
        assert parts[0] == "H"
        assert float(parts[1]) == pytest.approx(0.0)
        assert float(parts[3]) == pytest.approx(0.757)
        assert float(parts[5]) == pytest.approx(-0.469)


class TestMopacPresets:
    def _load_fn(self, settings_file):
        return _extract_method_as_fn(
            MOPAC_PATH,
            "MopacSetupDialog",
            "load_presets_from_file",
            extra_globals={"SETTINGS_FILE": str(settings_file)},
        )

    def _save_fn(self, settings_file):
        return _extract_method_as_fn(
            MOPAC_PATH,
            "MopacSetupDialog",
            "save_presets_to_file",
            extra_globals={"SETTINGS_FILE": str(settings_file), "QMessageBox": MagicMock()},
        )

    def test_round_trip(self, tmp_path):
        settings = tmp_path / "mopac.json"
        save = self._save_fn(settings)
        load = self._load_fn(settings)

        writer = MagicMock()
        writer.presets_data = {"My Preset": {"keywords": "PM6 PRECISE", "nosym": True}}
        save(writer)
        assert settings.exists()

        reader = MagicMock()
        load(reader)
        assert reader.presets_data == writer.presets_data
        reader.update_preset_combo.assert_called_once()

    def test_load_missing_file_gives_empty(self, tmp_path):
        load = self._load_fn(tmp_path / "absent.json")
        reader = MagicMock()
        load(reader)
        assert reader.presets_data == {}

    def test_load_corrupt_json_gives_empty(self, tmp_path):
        settings = tmp_path / "corrupt.json"
        settings.write_text("{not json!", encoding="utf-8")
        load = self._load_fn(settings)
        reader = MagicMock()
        load(reader)
        assert reader.presets_data == {}
