# -*- coding: utf-8 -*-
import os
import json
from PyQt6.QtWidgets import (QMessageBox, QDialog, QVBoxLayout, QLabel, 
                             QLineEdit, QSpinBox, QPushButton, QGroupBox, 
                             QHBoxLayout, QComboBox, QTextEdit, QFileDialog, QInputDialog, QSizePolicy, QCheckBox)
from PyQt6.QtGui import QPalette, QColor
from PyQt6.QtCore import Qt
from rdkit import Chem

PLUGIN_NAME = "MOPAC Input Generator"
PLUGIN_VERSION = "2026.01.03"
PLUGIN_AUTHOR = "HiroYokoyama"
PLUGIN_DESCRIPTION = "Generate MOPAC input files for semi-empirical calculations."
SETTINGS_FILE = os.path.join(os.path.dirname(__file__), "mopac_input_generator.json")

class MopacSetupDialog(QDialog):
    def __init__(self, parent=None, mol=None, filename=None):
        super().__init__(parent)
        self.setWindowTitle(PLUGIN_NAME)
        self.resize(500, 600)
        self.setWindowFlags(self.windowFlags() | Qt.WindowType.WindowMinMaxButtonsHint)
        self.setSizeGripEnabled(True)
        self.mol = mol
        self.filename = filename
        self.setup_ui()
        self.load_presets_from_file()
        self.calc_initial_charge_mult()

    def setup_ui(self):
        layout = QVBoxLayout()

        # --- Preset Management ---
        preset_group = QGroupBox("User Presets")
        # ... (rest of early setup is fine, handled by context)

    # Note: I need to target the setup_ui layout.addWidget(preview_group) specifically.
    # The REPLACE block above only handles __init__.
    # I will do two replacements to be safe or one large block? 
    # The file content is large. Two replacements is better.
    # First: __init__ updates.
    
    # Actually, I will just update __init__ here.
    # Then I will update the layout line separately.
    
    # Wait, I can't leave comments in replacement.
    
    # REPLACEMENT 1: __init__
        self.resize(500, 600)
        self.setWindowFlags(self.windowFlags() | Qt.WindowType.WindowMinMaxButtonsHint)
        self.setSizeGripEnabled(True)
        self.mol = mol
        self.filename = filename
        self.setup_ui()
        self.load_presets_from_file()
        self.calc_initial_charge_mult()

    def setup_ui(self):
        layout = QVBoxLayout()

        # --- Preset Management ---
        preset_group = QGroupBox("User Presets")
        preset_layout = QHBoxLayout()
        
        self.preset_combo = QComboBox()
        self.preset_combo.currentIndexChanged.connect(self.apply_selected_preset)
        preset_layout.addWidget(QLabel("Preset:"))
        preset_layout.addWidget(self.preset_combo, 1)

        self.btn_save_preset = QPushButton("Save New...")
        self.btn_save_preset.clicked.connect(self.save_preset_dialog)
        preset_layout.addWidget(self.btn_save_preset)

        self.btn_del_preset = QPushButton("Delete")
        self.btn_del_preset.clicked.connect(self.delete_preset)
        preset_layout.addWidget(self.btn_del_preset)

        preset_group.setLayout(preset_layout)
        layout.addWidget(preset_group)

        # --- Method Templates ---
        template_group = QGroupBox("Method Templates")
        template_layout = QHBoxLayout()
        self.template_combo = QComboBox()
        self.template_combo.addItems([
            "Select Template...",
            "Optimization (PM7)",
            "Optimization (PM6)",
            "Optimization (AM1)",
            "Single Point (PM7)",
            "Thermodynamics (PM7)",
            "Transition State (PM7 TS)"
        ])
        self.template_combo.currentIndexChanged.connect(self.apply_template)
        template_layout.addWidget(QLabel("Template:"))
        template_layout.addWidget(self.template_combo)
        template_group.setLayout(template_layout)
        layout.addWidget(template_group)

        # --- Keywords ---
        kw_group = QGroupBox("Keywords")
        kw_layout = QVBoxLayout()
        
        self.keywords_edit = QLineEdit("PM7 PRECISE")
        self.keywords_edit.textChanged.connect(self.update_preview)
        kw_layout.addWidget(QLabel("Keywords (Top Line):"))
        kw_layout.addWidget(self.keywords_edit)
        
        self.chk_nosym = QCheckBox("Disable Symmetry (NOSYM)")
        self.chk_nosym.setToolTip("Recommended for slightly distorted molecules to prevent errors.")
        self.chk_nosym.stateChanged.connect(self.update_preview)
        kw_layout.addWidget(self.chk_nosym)
        
        self.title_edit = QLineEdit("MOPAC Calculation")
        self.title_edit.textChanged.connect(self.update_preview)
        kw_layout.addWidget(QLabel("Title (Second Line):"))
        kw_layout.addWidget(self.title_edit)
        
        self.comment_edit = QLineEdit("Generated by MoleditPy")
        self.comment_edit.textChanged.connect(self.update_preview)
        kw_layout.addWidget(QLabel("Comment (Third Line):"))
        kw_layout.addWidget(self.comment_edit)
        
        kw_group.setLayout(kw_layout)
        layout.addWidget(kw_group)

        # --- Molecular State ---
        mol_group = QGroupBox("Molecular State")
        mol_layout = QHBoxLayout()
        
        self.charge_spin = QSpinBox()
        self.charge_spin.setRange(-10, 10)
        self.charge_spin.valueChanged.connect(self.validate_charge_mult)
        
        self.mult_spin = QSpinBox()
        self.mult_spin.setRange(1, 10)
        self.mult_spin.valueChanged.connect(self.validate_charge_mult)

        mol_layout.addWidget(QLabel("Charge:"))
        mol_layout.addWidget(self.charge_spin)
        mol_layout.addWidget(QLabel("Multiplicity:"))
        mol_layout.addWidget(self.mult_spin)
        
        self.default_palette = self.charge_spin.palette()
        mol_group.setLayout(mol_layout)
        layout.addWidget(mol_group)

        # --- Preview ---
        preview_group = QGroupBox("Preview")
        preview_layout = QVBoxLayout()
        self.preview_text = QTextEdit()
        self.preview_text.setReadOnly(False) # Editable
        self.preview_text.setMinimumHeight(200) # Adjusted height
        self.preview_text.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        preview_layout.addWidget(self.preview_text, 1)
        
        btn_refresh = QPushButton("Reset/Refresh Preview")
        btn_refresh.clicked.connect(self.update_preview)
        preview_layout.addWidget(btn_refresh)
        
        preview_group.setLayout(preview_layout)
        layout.addWidget(preview_group, 1)

        # --- Buttons ---
        btn_layout = QHBoxLayout()
        self.btn_save = QPushButton("Save Input File...")
        self.btn_save.clicked.connect(self.save_file)
        self.btn_save.setStyleSheet("font-weight: bold; padding: 5px;")
        btn_layout.addWidget(self.btn_save)
        layout.addLayout(btn_layout)

        self.setLayout(layout)
        self.update_preview()

    def calc_initial_charge_mult(self):
        if not self.mol: return
        try:
            charge = Chem.GetFormalCharge(self.mol)
            total_electrons = 0
            for atom in self.mol.GetAtoms():
                total_electrons += atom.GetAtomicNum()
            total_electrons -= charge
            
            # Simple multiplicity guess: 1 if even electrons, 2 if odd
            mult = 1 if total_electrons % 2 == 0 else 2
            
            self.charge_spin.setValue(charge)
            self.mult_spin.setValue(mult)
        except:
            pass

    def validate_charge_mult(self):
        self.update_keywords_charge_mult()
        self.update_preview()

    def update_keywords_charge_mult(self):
        # MOPAC handles charge and doublet/triplet etc via keywords sometimes, 
        # but CHARGE=n is standard. MS=n or SINGLET/DOUBLET/TRIPLET etc.
        # We will append CHARGE=n and Multiplicity keyword if needed
        pass

    def apply_template(self):
        txt = self.template_combo.currentText()
        if "Optimization (PM7)" in txt:
            self.keywords_edit.setText("PM7 PRECISE")
        elif "Optimization (PM6)" in txt:
            self.keywords_edit.setText("PM6 PRECISE")
        elif "Optimization (AM1)" in txt:
            self.keywords_edit.setText("AM1 PRECISE")
        elif "Single Point" in txt:
            self.keywords_edit.setText("PM7 1SCF")
        elif "Thermodynamics" in txt:
            self.keywords_edit.setText("PM7 THERMO")
        elif "Transition State" in txt:
            self.keywords_edit.setText("PM7 TS PRECISE")
        self.update_preview()

    def generate_content(self):
        lines = []
        
        # 1. Keywords
        base_kw = self.keywords_edit.text()
        charge = self.charge_spin.value()
        mult = self.mult_spin.value()
        
        # Add Charge
        kw_line = f"{base_kw} CHARGE={charge}"
        
        # Add NOSYM
        if self.chk_nosym.isChecked():
            kw_line += " NOSYM"
        
        # Add Multiplicity
        if mult == 1: kw_line += " SINGLET"
        elif mult == 2: kw_line += " DOUBLET"
        elif mult == 3: kw_line += " TRIPLET"
        elif mult == 4: kw_line += " QUARTET"
        elif mult == 5: kw_line += " QUINTET"
        elif mult == 6: kw_line += " SEXTET"
        else: kw_line += f" MS={float(mult-1)/2.0}"
        
        lines.append(kw_line)
        lines.append(self.title_edit.text())
        lines.append(self.comment_edit.text())
        
        # Geometry
        if self.mol:
            # Check for Single Point in keywords
            is_single_point = "1SCF" in base_kw.upper()
            opt_flag = "0" if is_single_point else "1"
            
            conf = self.mol.GetConformer()
            for i in range(self.mol.GetNumAtoms()):
                pos = conf.GetAtomPosition(i)
                atom = self.mol.GetAtomWithIdx(i)
                # Symbol X 1 Y 1 Z 1 (1 = optimize, 0 = fixed)
                symbol = atom.GetSymbol()
                lines.append(f"{symbol: <3} {pos.x: >10.5f} {opt_flag} {pos.y: >10.5f} {opt_flag} {pos.z: >10.5f} {opt_flag}")
                
        return "\n".join(lines)

    def update_preview(self):
        self.preview_text.setText(self.generate_content())

    def save_file(self):
        # Use content from preview text to allow manual edits
        content = self.preview_text.toPlainText()
        default_name = "mopac_job.mop"
        if self.filename:
            base = os.path.splitext(os.path.basename(self.filename))[0]
            default_name = f"{base}.mop"
            
        path, _ = QFileDialog.getSaveFileName(self, "Save MOPAC Input", default_name, "MOPAC Input (*.mop *.dat *.txt)")
        if path:
            try:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(content)
                QMessageBox.information(self, "Success", f"File saved to {path}")
                # Do not close dialog automatically
            except Exception as e:
                QMessageBox.critical(self, "Error", str(e))

    # --- Preset Management ---
    def load_presets_from_file(self):
        self.presets_data = {}
        if os.path.exists(SETTINGS_FILE):
            try:
                with open(SETTINGS_FILE, 'r', encoding='utf-8') as f:
                    self.presets_data = json.load(f)
            except Exception as e:
                print(f"Error loading presets: {e}")
        
        self.update_preset_combo()

    def update_preset_combo(self):
        current = self.preset_combo.currentText()
        self.preset_combo.blockSignals(True)
        self.preset_combo.clear()
        self.preset_combo.addItems(sorted(self.presets_data.keys()))
        
        if current in self.presets_data:
            self.preset_combo.setCurrentText(current)
        
        self.preset_combo.blockSignals(False)
        self.apply_selected_preset()

    def apply_selected_preset(self):
        name = self.preset_combo.currentText()
        if name not in self.presets_data: return
        data = self.presets_data[name]
        
        self.keywords_edit.setText(data.get("keywords", "PM7 PRECISE"))
        self.title_edit.setText(data.get("title", ""))
        self.comment_edit.setText(data.get("comment", ""))
        self.chk_nosym.setChecked(data.get("nosym", False))
        
        self.update_preview()
        
    def save_preset_dialog(self):
        name, ok = QInputDialog.getText(self, "Save Preset", "Preset Name:")
        if ok and name:
            self.presets_data[name] = {
                "keywords": self.keywords_edit.text(),
                "title": self.title_edit.text(),
                "comment": self.comment_edit.text(),
                "nosym": self.chk_nosym.isChecked()
            }
            self.save_presets_to_file()
            self.update_preset_combo()
            self.preset_combo.setCurrentText(name)

    def delete_preset(self):
        name = self.preset_combo.currentText()
        if not name: return
        
        confirm = QMessageBox.question(self, "Confirm", f"Delete preset '{name}'?")
        if confirm == QMessageBox.StandardButton.Yes:
            del self.presets_data[name]
            self.save_presets_to_file()
            self.update_preset_combo()

    def save_presets_to_file(self):
        try:
            with open(SETTINGS_FILE, 'w', encoding='utf-8') as f:
                json.dump(self.presets_data, f, indent=4)
        except Exception as e:
            QMessageBox.warning(self, "Error", f"Failed to save presets: {e}")

def run(mw):
    mol = getattr(mw, 'current_mol', None)
    if not mol:
        QMessageBox.warning(mw, PLUGIN_NAME, "No molecule loaded.")
        return
    filename = getattr(mw, 'current_file_path', None)
    dialog = MopacSetupDialog(parent=mw, mol=mol, filename=filename)
    dialog.exec()
