# -*- coding: utf-8 -*-
import os
from PyQt6.QtWidgets import (QMessageBox, QDialog, QVBoxLayout, QLabel, 
                             QLineEdit, QSpinBox, QPushButton, QFileDialog, 
                             QFormLayout, QGroupBox, QHBoxLayout, QTextEdit)
from PyQt6.QtCore import Qt

PLUGIN_NAME = "ORCA Input Generator"

class OrcaSetupDialog(QDialog):
    """
    ORCAインプット作成のための設定ダイアログ
    Advanced Blockや座標ブロック(* xyz ...)に対応
    """
    def __init__(self, parent=None, mol=None):
        super().__init__(parent)
        self.setWindowTitle("ORCA Input Setup")
        self.resize(500, 650)
        self.mol = mol
        self.setup_ui()

    def setup_ui(self):
        main_layout = QVBoxLayout()

        # ---------------------------------------------------------
        # 1. Resource Configuration (Parallel & Memory)
        # GUI順序変更: Parallel/Memory を一番上に
        # ---------------------------------------------------------
        res_group = QGroupBox("Parallelization & Memory")
        res_layout = QFormLayout()

        # Processors (%pal nprocs X end)
        self.nproc_spin = QSpinBox()
        self.nproc_spin.setRange(1, 128)
        self.nproc_spin.setValue(4)
        res_layout.addRow("Number of Processors (nprocs):", self.nproc_spin)

        # Memory (%maxcore) - ORCA defines memory PER CORE
        self.mem_spin = QSpinBox()
        self.mem_spin.setRange(100, 999999)
        self.mem_spin.setValue(2000) # Default 2000 MB
        self.mem_spin.setSuffix(" MB")
        res_layout.addRow("Memory per Core (%maxcore):", self.mem_spin)

        res_group.setLayout(res_layout)
        main_layout.addWidget(res_group)

        # ---------------------------------------------------------
        # 2. Simple Input Line (Keywords & Comment)
        # GUI順序変更: KeywordsとCommentを2番目に
        # ---------------------------------------------------------
        kw_group = QGroupBox("Simple Input Line (Keywords)")
        kw_layout = QVBoxLayout()
        
        # Keywords
        self.keywords_edit = QLineEdit("! B3LYP def2-SVP Opt Freq")
        self.keywords_edit.setPlaceholderText("! Functional Basis Opt ...")
        kw_layout.addWidget(QLabel("Keywords (starts with !):"))
        kw_layout.addWidget(self.keywords_edit)
        
        # Comment
        self.comment_edit = QLineEdit("Generated by MoleditPy Plugin")
        kw_layout.addWidget(QLabel("Comment (optional):"))
        kw_layout.addWidget(self.comment_edit)

        kw_group.setLayout(kw_layout)
        main_layout.addWidget(kw_group)

        # ---------------------------------------------------------
        # 3. Molecular State
        # ---------------------------------------------------------
        mol_group = QGroupBox("Molecular Specification")
        mol_layout = QHBoxLayout()
        
        # Charge
        self.charge_spin = QSpinBox()
        self.charge_spin.setRange(-10, 10)
        self.charge_spin.setValue(0)
        mol_layout.addWidget(QLabel("Charge:"))
        mol_layout.addWidget(self.charge_spin)

        # Multiplicity
        self.mult_spin = QSpinBox()
        self.mult_spin.setRange(1, 10)
        self.mult_spin.setValue(1)
        mol_layout.addWidget(QLabel("Multiplicity:"))
        mol_layout.addWidget(self.mult_spin)

        mol_group.setLayout(mol_layout)
        main_layout.addWidget(mol_group)

        # ---------------------------------------------------------
        # 4. Advanced Blocks
        # ---------------------------------------------------------
        # ORCA relies heavily on %block ... end syntax
        adv_group = QGroupBox("Advanced Blocks (Pre-Coordinates)")
        adv_layout = QVBoxLayout()
        
        help_label = QLabel("Enter advanced settings here (e.g., %scf, %basis, %geom, %output).\nThese will be written BEFORE the coordinate block.")
        help_label.setStyleSheet("color: gray; font-size: 10px;")
        adv_layout.addWidget(help_label)

        self.adv_edit = QTextEdit()
        self.adv_edit.setPlaceholderText("Example:\n%scf\n MaxIter 100\nend\n\n%output\n Print[P_Hirshfeld] 1\nend")
        adv_layout.addWidget(self.adv_edit)

        adv_group.setLayout(adv_layout)
        main_layout.addWidget(adv_group)

        # --- Save Button ---
        self.save_btn = QPushButton("Save Input File...")
        self.save_btn.clicked.connect(self.save_file)
        self.save_btn.setStyleSheet("font-weight: bold; padding: 5px;")
        main_layout.addWidget(self.save_btn)

        self.setLayout(main_layout)

    def get_coords_lines(self):
        """
        分子オブジェクトから原子座標の行リストを生成する
        """
        if not self.mol:
            return []
        
        lines = []
        try:
            conf = self.mol.GetConformer()
            for i in range(self.mol.GetNumAtoms()):
                pos = conf.GetAtomPosition(i)
                atom = self.mol.GetAtomWithIdx(i)
                symbol = atom.GetSymbol()
                # Symbol X Y Z formatted
                lines.append(f"  {symbol: <4} {pos.x: >12.6f} {pos.y: >12.6f} {pos.z: >12.6f}")
        except Exception as e:
            return [f"# Error extracting coordinates: {str(e)}"]
            
        return lines

    def save_file(self):
        # 座標データの準備
        coord_lines = self.get_coords_lines()
        if any("Error" in line for line in coord_lines):
            QMessageBox.critical(self, "Error", "\n".join(coord_lines))
            return

        # ファイル保存ダイアログ
        file_path, _ = QFileDialog.getSaveFileName(
            self, "Save ORCA Input", "", "ORCA Input (*.inp);;All Files (*)"
        )

        if file_path:
            try:
                with open(file_path, 'w', encoding='utf-8') as f:
                    # ---------------------------------------------------------
                    # 1. Resources (Parallel & Memory)
                    # ---------------------------------------------------------
                    nprocs = self.nproc_spin.value()
                    mem_mb = self.mem_spin.value()
                    
                    f.write(f"%maxcore {mem_mb}\n")
                    if nprocs > 1:
                        f.write(f"%pal nprocs {nprocs} end\n")

                    # ---------------------------------------------------------
                    # 2. Keywords Line
                    # ---------------------------------------------------------
                    kw_line = self.keywords_edit.text().strip()
                    if not kw_line.startswith("!"):
                        kw_line = "! " + kw_line
                    f.write(f"{kw_line}\n")

                    # ---------------------------------------------------------
                    # 3. Comment
                    # ---------------------------------------------------------
                    comment = self.comment_edit.text().strip()
                    if comment:
                        f.write(f"# {comment}\n")
                    
                    f.write("\n")

                    # ---------------------------------------------------------
                    # 4. Advanced Blocks (User Input)
                    # ---------------------------------------------------------
                    adv_content = self.adv_edit.toPlainText()
                    if adv_content.strip():
                        f.write(adv_content)
                        if not adv_content.endswith("\n"):
                            f.write("\n")
                        f.write("\n")

                    # ---------------------------------------------------------
                    # 5. Coordinate Block (* xyz charge mult)
                    # ---------------------------------------------------------
                    charge = self.charge_spin.value()
                    mult = self.mult_spin.value()
                    
                    f.write(f"* xyz {charge} {mult}\n")
                    for line in coord_lines:
                        f.write(line + "\n")
                    f.write("*\n")

                QMessageBox.information(self, "Success", f"File saved:\n{file_path}")
                self.accept()
            except Exception as e:
                QMessageBox.critical(self, "Error", f"Failed to save file:\n{str(e)}")

def run(main_window):
    """
    Entry point for the plugin.
    """
    mol = getattr(main_window, 'current_mol', None)
    
    if not mol or mol.GetNumAtoms() == 0:
        QMessageBox.warning(main_window, PLUGIN_NAME, "No molecule loaded or molecule is empty.")
        return

    dialog = OrcaSetupDialog(parent=main_window, mol=mol)
    dialog.exec()
    