# -*- coding: utf-8 -*-
import os
from PyQt6.QtWidgets import (QMessageBox, QDialog, QVBoxLayout, QLabel, 
                             QLineEdit, QSpinBox, QPushButton, QFileDialog, 
                             QFormLayout, QGroupBox, QHBoxLayout, QComboBox, QTextEdit)
from PyQt6.QtCore import Qt

PLUGIN_NAME = "Gaussian Input Generator"

class GaussianSetupDialog(QDialog):
    """
    Gaussianインプット作成のための高機能設定ダイアログ
    Link 0, Route, Title, Charge/Mult, および追記データに対応
    """
    def __init__(self, parent=None, mol=None):
        super().__init__(parent)
        self.setWindowTitle("Gaussian Input Setup (Advanced)")
        self.resize(500, 600) # 少し大きめに設定
        self.mol = mol
        self.setup_ui()

    def setup_ui(self):
        main_layout = QVBoxLayout()

        # --- 1. Link 0 Section (System Resources) ---
        link0_group = QGroupBox("Link 0 Commands (System Resources)")
        link0_layout = QFormLayout()

        # Memory
        mem_layout = QHBoxLayout()
        self.mem_spin = QSpinBox()
        self.mem_spin.setRange(1, 999999)
        self.mem_spin.setValue(4) # Default
        self.mem_unit = QComboBox()
        self.mem_unit.addItems(["GB", "MB", "MW"])
        mem_layout.addWidget(self.mem_spin)
        mem_layout.addWidget(self.mem_unit)
        link0_layout.addRow("Memory (%mem):", mem_layout)

        # Processors
        self.nproc_spin = QSpinBox()
        self.nproc_spin.setRange(1, 128)
        self.nproc_spin.setValue(4) # Default
        link0_layout.addRow("Processors (%nprocshared):", self.nproc_spin)
        
        # Checkpoint (Optional override)
        self.chk_edit = QLineEdit()
        self.chk_edit.setPlaceholderText("Auto-generated from filename if empty")
        link0_layout.addRow("Checkpoint (%chk):", self.chk_edit)

        link0_group.setLayout(link0_layout)
        main_layout.addWidget(link0_group)

        # --- 2. Job Specification (Route & Title) ---
        job_group = QGroupBox("Job Specification")
        job_layout = QFormLayout()

        # Route section
        self.keywords_edit = QLineEdit("#P B3LYP/6-31G(d) Opt Freq")
        job_layout.addRow("Route Section (#):", self.keywords_edit)

        # Title
        self.title_edit = QLineEdit("Generated by MoleditPy Plugin")
        job_layout.addRow("Title:", self.title_edit)

        job_group.setLayout(job_layout)
        main_layout.addWidget(job_group)

        # --- 3. Molecular State ---
        mol_group = QGroupBox("Molecular Specification")
        mol_layout = QHBoxLayout()
        
        # Charge
        self.charge_spin = QSpinBox()
        self.charge_spin.setRange(-10, 10)
        self.charge_spin.setValue(0)
        mol_layout.addWidget(QLabel("Charge:"))
        mol_layout.addWidget(self.charge_spin)

        # Multiplicity
        self.mult_spin = QSpinBox()
        self.mult_spin.setRange(1, 10)
        self.mult_spin.setValue(1)
        mol_layout.addWidget(QLabel("Multiplicity:"))
        mol_layout.addWidget(self.mult_spin)

        mol_group.setLayout(mol_layout)
        main_layout.addWidget(mol_group)

        # --- 4. Additional Input (The "Everything" section) ---
        tail_group = QGroupBox("Additional Input (Post-Coordinates)")
        tail_layout = QVBoxLayout()
        
        help_label = QLabel("For ModRedundant, Basis Sets (Gen), or Link1.\nAppended after the molecule specification.")
        help_label.setStyleSheet("color: gray; font-size: 10px;")
        tail_layout.addWidget(help_label)

        self.tail_edit = QTextEdit()
        self.tail_edit.setPlaceholderText("Example:\nD 1 2 3 4 S 10 10.0\n\nOr basis set data for Gen/GenECP...")
        tail_layout.addWidget(self.tail_edit)

        tail_group.setLayout(tail_layout)
        main_layout.addWidget(tail_group)

        # --- Save Button ---
        self.save_btn = QPushButton("Save Input File...")
        self.save_btn.clicked.connect(self.save_file)
        self.save_btn.setStyleSheet("font-weight: bold; padding: 5px;")
        main_layout.addWidget(self.save_btn)

        self.setLayout(main_layout)

    def get_coords_string(self):
        """
        分子オブジェクトから原子座標文字列を生成する
        """
        if not self.mol:
            return ""
        
        lines = []
        try:
            # RDKitの場合の座標取得
            conf = self.mol.GetConformer()
            for i in range(self.mol.GetNumAtoms()):
                pos = conf.GetAtomPosition(i)
                atom = self.mol.GetAtomWithIdx(i)
                symbol = atom.GetSymbol()
                # Symbol X Y Z formatted
                lines.append(f"{symbol: <4} {pos.x: >12.6f} {pos.y: >12.6f} {pos.z: >12.6f}")
        except Exception as e:
            return f"Error extracting coordinates: {str(e)}"
            
        return "\n".join(lines)

    def save_file(self):
        # 座標データの取得
        coords_block = self.get_coords_string()
        if "Error" in coords_block:
            QMessageBox.critical(self, "Error", coords_block)
            return

        # ファイル保存ダイアログ
        file_path, _ = QFileDialog.getSaveFileName(
            self, "Save Gaussian Input", "", "Gaussian Input (*.gjf *.com );;All Files (*)"
        )

        if file_path:
            try:
                # ファイル名に基づいてchk名を決定（ユーザー入力がない場合）
                filename_base = os.path.splitext(os.path.basename(file_path))[0]
                chk_name = self.chk_edit.text().strip()
                if not chk_name:
                    chk_name = f"{filename_base}.chk"
                # 拡張子がなければ付ける
                if not chk_name.endswith(".chk"):
                    chk_name += ".chk"

                with open(file_path, 'w', encoding='utf-8') as f:
                    # --- Link 0 Section ---
                    f.write(f"%nprocshared={self.nproc_spin.value()}\n")
                    f.write(f"%mem={self.mem_spin.value()}{self.mem_unit.currentText()}\n")
                    f.write(f"%chk={chk_name}\n")
                    
                    # --- Route Section ---
                    route_line = self.keywords_edit.text().strip()
                    if not route_line.startswith("#"):
                        route_line = "# " + route_line
                    f.write(f"{route_line}\n")
                    f.write("\n") # Blank line required
                    
                    # --- Title Section ---
                    title_line = self.title_edit.text().strip()
                    if not title_line:
                        title_line = "Gaussian Job"
                    f.write(f"{title_line}\n")
                    f.write("\n") # Blank line required
                    
                    # --- Charge & Multiplicity ---
                    f.write(f"{self.charge_spin.value()} {self.mult_spin.value()}\n")
                    
                    # --- Molecule Specification ---
                    f.write(coords_block)
                    f.write("\n") # Must end coord block with newline
                    
                    # --- Additional Input (Tail) ---
                    # ModRedundant, Basis Set data, etc.
                    tail_content = self.tail_edit.toPlainText()
                    if tail_content.strip():
                        # 前に空行が必要（座標ブロック終了のため）
                        f.write("\n") 
                        f.write(tail_content)
                        # 末尾が改行で終わるように調整
                        if not tail_content.endswith("\n"):
                            f.write("\n")
                    
                    # --- Final Blank Line ---
                    # Gaussian input files generally require empty lines at the end
                    f.write("\n")

                QMessageBox.information(self, "Success", f"File saved:\n{file_path}")
                self.accept()
            except Exception as e:
                QMessageBox.critical(self, "Error", f"Failed to save file:\n{str(e)}")

def run(main_window):
    """
    Entry point for the plugin.
    """
    mol = getattr(main_window, 'current_mol', None)
    
    if not mol or mol.GetNumAtoms() == 0:
        QMessageBox.warning(main_window, PLUGIN_NAME, "No molecule loaded or molecule is empty.")
        return

    dialog = GaussianSetupDialog(parent=main_window, mol=mol)
    dialog.exec()
    